//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChuyenKhoThuoc
    {
        public int ID { get; set; }
        public string MaDT { get; set; }
        public string MaKhoChuyen { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string MaKhoNhan { get; set; }
        public Nullable<System.DateTime> NgayChuyen { get; set; }
    
        public virtual DauThuoc DauThuoc { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual Kho Kho1 { get; set; }
    }
}
