//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTy
    {
        public string MaCongTy { get; set; }
        public string TenCongTy { get; set; }
        public string ToaDo1 { get; set; }
        public string ToaDo2 { get; set; }
        public string ToaDo3 { get; set; }
        public string ToaDo4 { get; set; }
    }
}
