//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonXuat()
        {
            this.ChiTietHoaDonXuat = new HashSet<ChiTietHoaDonXuat>();
        }
    
        public string MaHD { get; set; }
        public string MaKho { get; set; }
        public string MaTK { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string MaHoaDonMua { get; set; }
        public string MaHoaDonVanChuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonXuat> ChiTietHoaDonXuat { get; set; }
        public virtual HoaDonMua HoaDonMua { get; set; }
        public virtual HoaDonVanChuyen HoaDonVanChuyen { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
