//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonMua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonMua()
        {
            this.ChiTietHoaDonMua = new HashSet<ChiTietHoaDonMua>();
            this.HoaDonXuat = new HashSet<HoaDonXuat>();
        }
    
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string MaTK { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string MaKho { get; set; }
        public string MaHoaDonVanChuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonMua> ChiTietHoaDonMua { get; set; }
        public virtual HoaDonVanChuyen HoaDonVanChuyen { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonXuat> HoaDonXuat { get; set; }
    }
}
