//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonVanChuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonVanChuyen()
        {
            this.HoaDonMua = new HashSet<HoaDonMua>();
            this.HoaDonXuat = new HashSet<HoaDonXuat>();
        }
    
        public string MaHoaDonVanChuyen { get; set; }
        public string MaNguoiVanChuyen { get; set; }
        public Nullable<System.DateTime> NgayGioVanChuyen { get; set; }
        public Nullable<int> SoGioDuTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonMua> HoaDonMua { get; set; }
        public virtual VanChuyen VanChuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonXuat> HoaDonXuat { get; set; }
    }
}
