//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoachLamViec
    {
        public string ID { get; set; }
        public string CongViec { get; set; }
        public Nullable<int> TrangThai1 { get; set; }
        public Nullable<int> TrangThai2 { get; set; }
        public string GhiChu { get; set; }
        public string MaTD { get; set; }
    
        public virtual TrinhDuoc TrinhDuoc { get; set; }
    }
}
