//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoNhanVien
    {
        public int ID { get; set; }
        public string MaKho { get; set; }
        public string MaTK { get; set; }
        public string ChucVu { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
