//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMaiDauThuoc
    {
        public string ID { get; set; }
        public string MaKM { get; set; }
        public string MaDT { get; set; }
    
        public virtual DauThuoc DauThuoc { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
