//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomQuyenRoute
    {
        public int ID { get; set; }
        public Nullable<int> MaNhomQuyen { get; set; }
        public Nullable<int> IDRoute { get; set; }
    
        public virtual NhomQuyen NhomQuyen { get; set; }
        public virtual Route Route { get; set; }
    }
}
