//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanHuyen
    {
        public int ID { get; set; }
        public string TenQuanHuyen { get; set; }
        public Nullable<int> IDTinhThanh { get; set; }
    
        public virtual TinhThanhPho TinhThanhPho { get; set; }
    }
}
