//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsDThuocNThuoc
    {
        public int ID { get; set; }
        public string MaDauThuoc { get; set; }
        public string MaNhomThuoc { get; set; }
        public string TenDinhNghia { get; set; }
    
        public virtual DauThuoc DauThuoc { get; set; }
        public virtual NhomDauThuoc NhomDauThuoc { get; set; }
    }
}
