//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuChi
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Loai { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NguoiLap { get; set; }
        public Nullable<int> GiaTri { get; set; }
    }
}
