//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyduoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrinhDuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrinhDuoc()
        {
            this.KeHoachLamViec = new HashSet<KeHoachLamViec>();
            this.TaiKhoan = new HashSet<TaiKhoan>();
            this.TrinhDuocKhachHang = new HashSet<TrinhDuocKhachHang>();
        }
    
        public string MaTD { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string KhuVuc { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<int> LuongTieuThu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachLamViec> KeHoachLamViec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrinhDuocKhachHang> TrinhDuocKhachHang { get; set; }
    }
}
